version: '3.9'
services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: tenxers
      POSTGRES_USER: tenxers
      POSTGRES_PASSWORD: tenxers
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
